config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :notes

  root 'home#top'
  get '/about' => 'home#about'

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	validates :content, presence: true, length: {maximum: 140}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :notes
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@message = "ようこそGatebookへ！"
  end

  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @notes = @user.notes
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'ユーザーが保存されました'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'ユーザーが削除されました'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="container">
  <h1>Gatebookとは？</h1>
  <p>GatebookとはRuby on Railsというフレームワークを駆使した、
記事投稿SNSサービスです。
近況やつぶやきを投稿し、サービス上の友達と楽しくコミュニケーションできます。</p>
</div>

app/views/home/top.html.erb
  <h1><%= @message %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar">
  <div class="container">
    <div id="logo">Gatebook</div>
    <ul class="header-right">
      <li><%= link_to "Top", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "New", new_note_path %></li>
      <li><%= link_to "Index", notes_path %></li>
      <li><%= link_to "Users", users_path %></li>
    </ul>
  </div>
</header>

<div class="container">
 <%= yield %>
</div>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
	<% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @note.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  ユーザーID
  <%= f.collection_select :user_id, User.all, :id, :id, {prompt: true}, {class: "form-control user-id-field"} %>
	タイトル
	<%= f.text_field :title, class: "form-control title-field" %>
	内容
	<%= f.text_area :content, class: "form-control content-field" %>
	<%= f.submit "保存", class: "btn primary-btn" %>
<% end %>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <% @notes.each do |note| %>
    <li>
      <span class="user-name">
        <%= note.user.name %>
      </span>
      <span class="content">
        <%= link_to note.title, note_path(note.id) %>
      </span>
    </li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice" class="alert alert-success">
  <%= notice %>
</p>
<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>
<%= link_to '新規ユーザー作成', new_user_path, class: "btn add-user-btn" %>

<ul class="user-list">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> |
      <%= user.email %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<aside class="sidebar">
  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>

  <section>
    <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
  </section>

</aside>

<ul class="notes">
  <% @notes.each do |note| %>
   <li><%= link_to note.title, note %></li>
   <% end %>
</ul>